### ISSUE TITLE
'onHeartbeat' failed 'ValueError'

### ISSUE THREAD

**Issue by koenkooi** [GameDevHobby/lgtv-webos-domoticz-plugin#1]
I installed the plugin yesterday and noticed some issues, one of them being this:
```
Nov 07 20:56:06 domoticz-gateway domoticz[27746]: (55" LG TV) Update 1:'com.webos.app.hdmi2
                                                  ' (55" LG TV - Status)
Nov 07 20:57:45 domoticz-gateway domoticz[27746]: (55" LG TV) Update 1:'netflix
                                                  ' (55" LG TV - Status)
Nov 07 20:58:33 domoticz-gateway domoticz[27746]: (55" LG TV) Update 1:'Traceback (most recent call last):
                                                  )' (55" LG TV - Status)
Nov 07 20:58:33 domoticz-gateway domoticz[27746]: (55" LG TV) Update 1:'10' (55" LG TV - Source)
Nov 07 20:58:41 domoticz-gateway domoticz[27746]: (55" LG TV) 'onHeartbeat' failed 'ValueError':'invalid literal for int() with base 10: 'Traceback (most recent call last):\n  File "/var/lib/domoticz/plugins/lgtv/lg.py", line 194, in <module>\n    main()\n  File "/var/lib/domoticz/plugins/lgtv/lg.py", line 189, in main\n    print(cmd.r'.
Nov 07 20:58:41 domoticz-gateway domoticz[27746]: (55" LG TV) ----> Line 366 in /var/lib/domoticz/plugins/lgtv/plugin.py, function onHeartbeat
Nov 07 20:58:41 domoticz-gateway domoticz[27746]: (55" LG TV) ----> Line 259 in /var/lib/domoticz/plugins/lgtv/plugin.py, function onHeartbeat
Nov 07 20:58:41 domoticz-gateway domoticz[27746]: (55" LG TV) ----> Line 343 in /var/lib/domoticz/plugins/lgtv/plugin.py, function GetTVInfo
Nov 07 20:58:45 domoticz-gateway domoticz[27746]: (55" LG TV) Update 0:'Off' (55" LG TV - Status)

```

**Comment by GameDevHobby** [comment]
Thanks for getting into my plugin! I will merge your pull request! May I ask what the value was that was invalid?

**Comment by koenkooi** [comment]
Thanks for meeging it! I haven’t looked at what the value was, the isdigit() worked on the first try and I forgot to inspect the value after that.
